ALTER TABLE profiles
DROP COLUMN IF EXISTS x,
DROP COLUMN IF EXISTS instagram,
DROP COLUMN IF EXISTS tiktok,
DROP COLUMN IF EXISTS youtube,
DROP COLUMN IF EXISTS snapchat,
DROP COLUMN IF EXISTS whatsapp;
